name: pr_pg26
channels:
  - conda-forge
dependencies:
  - python=3.14
  - kagglehub
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - chainer
  - nbformat
  - xgboost
  - shap
  - optuna
  - optuna-integration
  # - ydata-profiling
  # - dask

  